// Seed data — only used the FIRST time the site runs, to seed the rates
// table in Neon (Postgres). After that, everything here is fully editable
// from /admin/rates and lives in the database instead.

export const DEFAULT_SETTINGS = {
  gstRate: 0.05,
};

export const DEFAULT_VEHICLES = {
  sedan: {
    label: 'Sedan',
    subLabel: 'Swift Dzire, Etios, Nissan Sunny or equivalent',
    seats: 4,
    tripTypes: ['airport', 'local', 'outstation', 'oneway'],
    enquiryOnly: false,
    airport: { minKm: 30, ratePerKm: 34 },
    local: {
      packages: [
        { hrs: 4, km: 40, price: 1500 },
        { hrs: 8, km: 80, price: 2500 },
        { hrs: 12, km: 120, price: 3600 },
      ],
      extraKmRate: 20,
      extraHrRate: 200,
    },
    outstation: { minKmPerDay: 300, ratePerKm: 13, da: 400 },
    oneWay: { minKm: 150, ratePerKm: 17, da: 400 },
  },
  suv: {
    label: 'SUV',
    subLabel: 'Ertiga, Innova or equivalent',
    seats: 7,
    tripTypes: ['airport', 'local', 'outstation', 'oneway'],
    enquiryOnly: false,
    airport: { minKm: 30, ratePerKm: 50 },
    local: {
      packages: [
        { hrs: 4, km: 40, price: 2500 },
        { hrs: 8, km: 80, price: 3100 },
        { hrs: 12, km: 120, price: 4800 },
      ],
      extraKmRate: 25,
      extraHrRate: 250,
    },
    outstation: { minKmPerDay: 300, ratePerKm: 17, da: 400 },
    oneWay: { minKm: 150, ratePerKm: 22, da: 400 },
  },
  crysta: {
    label: 'Innova Crysta',
    subLabel: 'Premium 7-seater',
    seats: 7,
    tripTypes: ['airport', 'local', 'outstation', 'oneway'],
    enquiryOnly: false,
    airport: { minKm: 30, ratePerKm: 63 },
    local: {
      packages: [
        { hrs: 8, km: 80, price: 4000 },
        { hrs: 12, km: 120, price: 6000 },
      ],
      extraKmRate: 30,
      extraHrRate: 300,
    },
    outstation: { minKmPerDay: 300, ratePerKm: 22, da: 500 },
    oneWay: { minKm: 150, ratePerKm: 30, da: 400 },
  },
  tt_ac: {
    label: 'Tempo Traveller — AC',
    subLabel: '12–17 seater, AC',
    seats: 12,
    tripTypes: ['airport', 'local', 'outstation'],
    enquiryOnly: false,
    airport: { flat: 5600, minKm: 30 },
    local: {
      packages: [{ hrs: 8, km: 80, price: 5600 }],
      extraKmRate: 30,
      extraHrRate: 300,
    },
    outstation: { minKmPerDay: 300, ratePerKm: 25, da: 500 },
  },
  tt_non_ac: {
    label: 'Tempo Traveller — Non AC',
    subLabel: '12–17 seater, Non AC',
    seats: 12,
    tripTypes: ['airport', 'local', 'outstation'],
    enquiryOnly: false,
    airport: { flat: 4900, minKm: 30 },
    local: {
      packages: [{ hrs: 8, km: 80, price: 4900 }],
      extraKmRate: 30,
      extraHrRate: 300,
    },
    outstation: { minKmPerDay: 300, ratePerKm: 22, da: 500 },
  },
  // ---------------------------------------------------------------------
  // Added in the 2026 redesign so every fleet vehicle is bookable online.
  // ⚠ STARTER PRICES — please set the real rates in /admin/rates.
  // Existing databases pick these up automatically (see rates-store.js).
  // ---------------------------------------------------------------------
  innova_hycross_hybrid: {
    label: 'Innova Hycross Hybrid',
    subLabel: 'Premium hybrid 7-seater',
    seats: 7,
    tripTypes: ['airport', 'local', 'outstation', 'oneway'],
    enquiryOnly: false,
    airport: { minKm: 30, ratePerKm: 65 },
    local: {
      packages: [
        { hrs: 8, km: 80, price: 4300 },
        { hrs: 12, km: 120, price: 6400 },
      ],
      extraKmRate: 32,
      extraHrRate: 320,
    },
    outstation: { minKmPerDay: 300, ratePerKm: 24, da: 500 },
    oneWay: { minKm: 150, ratePerKm: 32, da: 400 },
  },
  urbania_9_seater: {
    label: 'Urbania 9 Seater',
    subLabel: 'Force Urbania, premium AC van',
    seats: 9,
    tripTypes: ['airport', 'local', 'outstation'],
    enquiryOnly: false,
    airport: { flat: 6500, minKm: 30 },
    local: { packages: [{ hrs: 8, km: 80, price: 6500 }], extraKmRate: 35, extraHrRate: 400 },
    outstation: { minKmPerDay: 300, ratePerKm: 30, da: 600 },
  },
  urbania_12_seater: {
    label: 'Urbania 12 Seater',
    subLabel: 'Force Urbania, premium AC van',
    seats: 12,
    tripTypes: ['airport', 'local', 'outstation'],
    enquiryOnly: false,
    airport: { flat: 7000, minKm: 30 },
    local: { packages: [{ hrs: 8, km: 80, price: 7000 }], extraKmRate: 38, extraHrRate: 450 },
    outstation: { minKmPerDay: 300, ratePerKm: 32, da: 600 },
  },
  urbania_16_seater: {
    label: 'Urbania 16 Seater',
    subLabel: 'Force Urbania, premium AC van',
    seats: 16,
    tripTypes: ['airport', 'local', 'outstation'],
    enquiryOnly: false,
    airport: { flat: 7800, minKm: 30 },
    local: { packages: [{ hrs: 8, km: 80, price: 7800 }], extraKmRate: 40, extraHrRate: 500 },
    outstation: { minKmPerDay: 300, ratePerKm: 35, da: 600 },
  },
  urbania_17_seater: {
    label: 'Urbania 17 Seater',
    subLabel: 'Force Urbania, premium AC van',
    seats: 17,
    tripTypes: ['airport', 'local', 'outstation'],
    enquiryOnly: false,
    airport: { flat: 8000, minKm: 30 },
    local: { packages: [{ hrs: 8, km: 80, price: 8000 }], extraKmRate: 40, extraHrRate: 500 },
    outstation: { minKmPerDay: 300, ratePerKm: 36, da: 600 },
  },
  urbania_luxury: {
    label: 'Urbania Luxury',
    subLabel: 'Force Urbania with luxury captain seats',
    seats: 10,
    tripTypes: ['airport', 'local', 'outstation'],
    enquiryOnly: false,
    airport: { flat: 9000, minKm: 30 },
    local: { packages: [{ hrs: 8, km: 80, price: 9000 }], extraKmRate: 45, extraHrRate: 550 },
    outstation: { minKmPerDay: 300, ratePerKm: 42, da: 700 },
  },
  tempo_traveller_20_seater_ac: {
    label: 'Tempo Traveller 20 Seater — AC',
    subLabel: '20 seater, AC',
    seats: 20,
    tripTypes: ['airport', 'local', 'outstation'],
    enquiryOnly: false,
    airport: { flat: 6500, minKm: 30 },
    local: { packages: [{ hrs: 8, km: 80, price: 6500 }], extraKmRate: 34, extraHrRate: 350 },
    outstation: { minKmPerDay: 300, ratePerKm: 28, da: 500 },
  },
  tempo_traveller_20_seater_non_ac: {
    label: 'Tempo Traveller 20 Seater — Non AC',
    subLabel: '20 seater, Non AC',
    seats: 20,
    tripTypes: ['airport', 'local', 'outstation'],
    enquiryOnly: false,
    airport: { flat: 5800, minKm: 30 },
    local: { packages: [{ hrs: 8, km: 80, price: 5800 }], extraKmRate: 32, extraHrRate: 330 },
    outstation: { minKmPerDay: 300, ratePerKm: 25, da: 500 },
  },
  // ---------------------------------------------------------------------
  // Added in the 2026 redesign so every fleet vehicle can be booked online.
  // ⚠ STARTER RATES — please check every number in /admin/rates and change
  // them to your real prices. They sync into the database automatically.
  // ---------------------------------------------------------------------
  innova_hycross_hybrid: {
    label: 'Innova Hycross Hybrid',
    subLabel: 'Premium hybrid 7-seater',
    seats: 7,
    tripTypes: ['airport', 'local', 'outstation', 'oneway'],
    enquiryOnly: false,
    airport: { minKm: 30, ratePerKm: 66 },
    local: {
      packages: [
        { hrs: 8, km: 80, price: 4300 },
        { hrs: 12, km: 120, price: 6400 },
      ],
      extraKmRate: 32,
      extraHrRate: 320,
    },
    outstation: { minKmPerDay: 300, ratePerKm: 24, da: 500 },
    oneWay: { minKm: 150, ratePerKm: 32, da: 400 },
  },
  urbania_9_seater: {
    label: 'Force Urbania 9 Seater',
    subLabel: 'Luxury van, AC, pushback seats',
    seats: 9,
    tripTypes: ['airport', 'local', 'outstation'],
    enquiryOnly: false,
    airport: { flat: 6200, minKm: 30 },
    local: { packages: [{ hrs: 8, km: 80, price: 6800 }, { hrs: 12, km: 120, price: 9500 }], extraKmRate: 36, extraHrRate: 400 },
    outstation: { minKmPerDay: 300, ratePerKm: 30, da: 600 },
  },
  urbania_12_seater: {
    label: 'Force Urbania 12 Seater',
    subLabel: 'Luxury van, AC, pushback seats',
    seats: 12,
    tripTypes: ['airport', 'local', 'outstation'],
    enquiryOnly: false,
    airport: { flat: 6800, minKm: 30 },
    local: { packages: [{ hrs: 8, km: 80, price: 7500 }, { hrs: 12, km: 120, price: 10500 }], extraKmRate: 38, extraHrRate: 400 },
    outstation: { minKmPerDay: 300, ratePerKm: 32, da: 600 },
  },
  urbania_16_seater: {
    label: 'Force Urbania 16 Seater',
    subLabel: 'Luxury van, AC, pushback seats',
    seats: 16,
    tripTypes: ['airport', 'local', 'outstation'],
    enquiryOnly: false,
    airport: { flat: 7500, minKm: 30 },
    local: { packages: [{ hrs: 8, km: 80, price: 8200 }, { hrs: 12, km: 120, price: 11500 }], extraKmRate: 40, extraHrRate: 450 },
    outstation: { minKmPerDay: 300, ratePerKm: 35, da: 600 },
  },
  urbania_17_seater: {
    label: 'Force Urbania 17 Seater',
    subLabel: 'Luxury van, AC, pushback seats',
    seats: 17,
    tripTypes: ['airport', 'local', 'outstation'],
    enquiryOnly: false,
    airport: { flat: 7800, minKm: 30 },
    local: { packages: [{ hrs: 8, km: 80, price: 8500 }, { hrs: 12, km: 120, price: 12000 }], extraKmRate: 40, extraHrRate: 450 },
    outstation: { minKmPerDay: 300, ratePerKm: 36, da: 600 },
  },
  urbania_luxury: {
    label: 'Force Urbania Luxury',
    subLabel: 'Premium lounge interiors, 10 seater',
    seats: 10,
    tripTypes: ['airport', 'local', 'outstation'],
    enquiryOnly: false,
    airport: { flat: 8500, minKm: 30 },
    local: { packages: [{ hrs: 8, km: 80, price: 9500 }, { hrs: 12, km: 120, price: 13500 }], extraKmRate: 45, extraHrRate: 500 },
    outstation: { minKmPerDay: 300, ratePerKm: 42, da: 700 },
  },
  tempo_traveller_20_seater_ac: {
    label: 'Tempo Traveller 20 Seater — AC',
    subLabel: '20 seater, AC',
    seats: 20,
    tripTypes: ['airport', 'local', 'outstation'],
    enquiryOnly: false,
    airport: { flat: 6500, minKm: 30 },
    local: { packages: [{ hrs: 8, km: 80, price: 6500 }], extraKmRate: 34, extraHrRate: 350 },
    outstation: { minKmPerDay: 300, ratePerKm: 28, da: 500 },
  },
  tempo_traveller_20_seater_non_ac: {
    label: 'Tempo Traveller 20 Seater — Non AC',
    subLabel: '20 seater, Non AC',
    seats: 20,
    tripTypes: ['airport', 'local', 'outstation'],
    enquiryOnly: false,
    airport: { flat: 5800, minKm: 30 },
    local: { packages: [{ hrs: 8, km: 80, price: 5800 }], extraKmRate: 32, extraHrRate: 350 },
    outstation: { minKmPerDay: 300, ratePerKm: 25, da: 500 },
  },
  // Buses stay enquiry-only ("Request Quote"). They're listed for every trip
  // type so customers see them on /select-cars too.
  mini_bus_21_ac: { label: 'Mini Bus 21 Seater — AC', subLabel: 'Group travel', seats: 21, tripTypes: ['airport', 'local', 'outstation', 'oneway', 'group'], enquiryOnly: true },
  mini_bus_21_non_ac: { label: 'Mini Bus 21 Seater — Non AC', subLabel: 'Group travel', seats: 21, tripTypes: ['airport', 'local', 'outstation', 'oneway', 'group'], enquiryOnly: true },
  mini_bus_33_ac: { label: 'Mini Bus 33 Seater — AC', subLabel: 'Group travel', seats: 33, tripTypes: ['airport', 'local', 'outstation', 'oneway', 'group'], enquiryOnly: true },
  mini_bus_33_non_ac: { label: 'Mini Bus 33 Seater — Non AC', subLabel: 'Group travel', seats: 33, tripTypes: ['airport', 'local', 'outstation', 'oneway', 'group'], enquiryOnly: true },
  bus_50_ac: { label: 'Bus 50 Seater — AC', subLabel: 'Group travel', seats: 50, tripTypes: ['airport', 'local', 'outstation', 'oneway', 'group'], enquiryOnly: true },
  bus_50_non_ac: { label: 'Bus 50 Seater — Non AC', subLabel: 'Group travel', seats: 50, tripTypes: ['airport', 'local', 'outstation', 'oneway', 'group'], enquiryOnly: true },
};
